name: .NET Core CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      sql-server:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - 1433:1433
        options: >-
          --env ACCEPT_EULA=Y
          --env SA_PASSWORD=YourStrong!Passw0rd
          --health-cmd="wait-for-it localhost:1433 --timeout=60 -- echo 'SQL Server is up'" 
          --health-interval=10s
          --health-retries=5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping || exit 1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release --no-build
